### ISSUE TITLE
BTC Transfer Error!

### ISSUE THREAD

**Issue by Vvonrth** [GemWallet/gemwallet-website#55]
![IMG_9031](https://github.com/GemWallet/gemwallet-website/assets/170835101/5aa64ead-5a1f-4ff9-ba81-4246c28824c8)

i tried to change around the quantity of BTC, also tried different wallet addresses, nothing changes!!  help!!!!
![IMG_9031](https://github.com/GemWallet/gemwallet-website/assets/170835101/2ec58aa9-f181-4bc9-9eba-94e8dea57797)

**Comment by bthibaut** [comment]
Hello, this GitHub is about [GemWallet.app](https://gemwallet.app/) which is a Chrome extension for the XRPL. You are talking about another GemWallet project which is not us. Please contact the devs of the mobile app you are using please 👍
